# Site settings
title: Brendan Thompson's Website
description: Brendan Thompson's personal blog
url: "brendev.co"
permalink: pretty

# Sass
sass:
    sass_dir: _sass

# Navigation Bar
# navigation-header:
#   Home: /
#   Posts: /posts/
#   Categories: /Categories/
#   Projects: /projects/

# User settings
username: Brendan Thompson
user_title: Software Developer
email: brenthompson2@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
